// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6nSp6VoY_oMGNvAKHibB2--e5unr59-c',
    appId: '1:481680290058:web:5b695377bd8d08fecd4af3',
    messagingSenderId: '481680290058',
    projectId: 'instagramauth-8e8b8',
    authDomain: 'instagramauth-8e8b8.firebaseapp.com',
    storageBucket: 'instagramauth-8e8b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dyi-IdqmHqNNVqFGopKF47gmlyRjEXk',
    appId: '1:481680290058:android:7a422526bc4dce5dcd4af3',
    messagingSenderId: '481680290058',
    projectId: 'instagramauth-8e8b8',
    storageBucket: 'instagramauth-8e8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuRvScqDTAFYjA9ogZMAg_dh_6_IIK1vM',
    appId: '1:481680290058:ios:a0f6747dec2cdb82cd4af3',
    messagingSenderId: '481680290058',
    projectId: 'instagramauth-8e8b8',
    storageBucket: 'instagramauth-8e8b8.appspot.com',
    iosClientId: '481680290058-hl381fo35iehjcua3uvb707igs93lh7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuRvScqDTAFYjA9ogZMAg_dh_6_IIK1vM',
    appId: '1:481680290058:ios:a0f6747dec2cdb82cd4af3',
    messagingSenderId: '481680290058',
    projectId: 'instagramauth-8e8b8',
    storageBucket: 'instagramauth-8e8b8.appspot.com',
    iosClientId: '481680290058-hl381fo35iehjcua3uvb707igs93lh7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramui',
  );
}
